pref("extensions.zotfile.source_dir_ff",true);
pref("extensions.zotfile.source_dir","");
pref("extensions.zotfile.dest_dir", "");
pref("extensions.zotfile.filetypes", "pdf,doc,txt,rtf");
pref("extensions.zotfile.useFilestypesForBatch", true);
pref("extensions.zotfile.allFiles", false);
pref("extensions.zotfile.useZoteroToRename", false);
pref("extensions.zotfile.renameFormat", "%a_%y_%t");
pref("extensions.zotfile.renameFormat_patent", "%a_%y_%t"); 
pref("extensions.zotfile.truncate_title", true);
pref("extensions.zotfile.truncate_smart", true);
pref("extensions.zotfile.max_titlelength", 80);
pref("extensions.zotfile.max_authors", 2);
pref("extensions.zotfile.add_etal", true);
pref("extensions.zotfile.etal", " et al");
pref("extensions.zotfile.confirmation", true);     
pref("extensions.zotfile.confirmation_batch_ask", true);     
pref("extensions.zotfile.confirmation_batch", 2);
pref("extensions.zotfile.import", true);
pref("extensions.zotfile.replace_blanks", false);
pref("extensions.zotfile.subfolder", false);
pref("extensions.zotfile.subfolderFormat", "/%w/%y");  
pref("extensions.zotfile.userInput", false);
pref("extensions.zotfile.userInput_Default", "Paper");
pref("extensions.zotfile.firstuse", true);
